/**
 * Theme constants — TypeScript mirror of docs/11_DESIGN_TOKENS.md
 *
 * Use CSS variable references for runtime styling.
 * Use TOKEN keys for type-safe token name lookup (tests, docs, tooling).
 */

export const TOKEN = {
  color: {
    bgBase: "--color-bg-base",
    bgRecessed: "--color-bg-recessed",
    bgSurface: "--color-bg-surface",
    bgElevated: "--color-bg-elevated",
    bgOverlay: "--color-bg-overlay",
    accent: "--color-accent",
    accentHover: "--color-accent-hover",
    accentMuted: "--color-accent-muted",
    accentSubtle: "--color-accent-subtle",
    accentBorder: "--color-accent-border",
    accentFocus: "--color-accent-focus",
    textPrimary: "--color-text-primary",
    textSecondary: "--color-text-secondary",
    textTertiary: "--color-text-tertiary",
    textDisabled: "--color-text-disabled",
    textInverse: "--color-text-inverse",
    textCode: "--color-text-code",
    statusOperational: "--color-status-operational",
    statusWarning: "--color-status-warning",
    statusCritical: "--color-status-critical",
    statusInfo: "--color-status-info",
    statusInProgress: "--color-status-in-progress",
    statusArchived: "--color-status-archived",
    success: "--color-success",
    error: "--color-error",
    link: "--color-link",
    linkHover: "--color-link-hover",
    glassHeader: "--color-glass-header",
    glassBackdrop: "--color-glass-backdrop",
  },
  font: {
    sans: "--font-sans",
    mono: "--font-mono",
    sizeDisplay: "--font-size-display",
    sizeDisplayMobile: "--font-size-display-mobile",
    sizeHeadingLg: "--font-size-heading-lg",
    sizeHeadingMd: "--font-size-heading-md",
    sizeHeadingSm: "--font-size-heading-sm",
    sizeBodyLg: "--font-size-body-lg",
    sizeBody: "--font-size-body",
    sizeBodySm: "--font-size-body-sm",
    sizeLabel: "--font-size-label",
    sizeMono: "--font-size-mono",
    sizeMonoSm: "--font-size-mono-sm",
    sizeMetric: "--font-size-metric",
    weightRegular: "--font-weight-regular",
    weightMedium: "--font-weight-medium",
  },
  lineHeight: {
    display: "--line-height-display",
    heading: "--line-height-heading",
    body: "--line-height-body",
    compact: "--line-height-compact",
    mono: "--line-height-mono",
  },
  letterSpacing: {
    tight: "--letter-spacing-tight",
    snug: "--letter-spacing-snug",
    normal: "--letter-spacing-normal",
    wide: "--letter-spacing-wide",
  },
  space: {
    0: "--space-0",
    1: "--space-1",
    2: "--space-2",
    3: "--space-3",
    4: "--space-4",
    5: "--space-5",
    6: "--space-6",
    8: "--space-8",
    10: "--space-10",
    12: "--space-12",
    16: "--space-16",
    20: "--space-20",
    24: "--space-24",
    32: "--space-32",
  },
  radius: {
    none: "--radius-none",
    sm: "--radius-sm",
    md: "--radius-md",
    lg: "--radius-lg",
    xl: "--radius-xl",
    full: "--radius-full",
  },
  border: {
    rest: "--border-rest",
    hover: "--border-hover",
    active: "--border-active",
    accent: "--border-accent",
    focus: "--border-focus",
    widthDefault: "--border-width-default",
    widthFocus: "--border-width-focus",
    widthAccentRail: "--border-width-accent-rail",
    strokeIcon: "--stroke-icon",
  },
  shadow: {
    none: "--shadow-none",
    modal: "--shadow-modal",
    statusPulse: "--shadow-status-pulse",
  },
  blur: {
    none: "--blur-none",
    header: "--blur-header",
    overlay: "--blur-overlay",
    imagePlaceholder: "--blur-image-placeholder",
  },
  opacity: {
    disabled: "--opacity-disabled",
    muted: "--opacity-muted",
    hover: "--opacity-hover",
    noise: "--opacity-noise",
    grid: "--opacity-grid",
    signalLine: "--opacity-signal-line",
    backdrop: "--opacity-backdrop",
  },
  motion: {
    durationInstant: "--motion-duration-instant",
    durationFast: "--motion-duration-fast",
    durationBase: "--motion-duration-base",
    durationSlow: "--motion-duration-slow",
    durationReveal: "--motion-duration-reveal",
    durationCounter: "--motion-duration-counter",
    durationPulse: "--motion-duration-pulse",
    durationPulseInterval: "--motion-duration-pulse-interval",
    easeDefault: "--motion-ease-default",
    easeEnter: "--motion-ease-enter",
    translateYMax: "--motion-translate-y-max",
    cardLift: "--motion-card-lift",
  },
  z: {
    base: "--z-base",
    recessed: "--z-recessed",
    header: "--z-header",
    statusBar: "--z-status-bar",
    dropdown: "--z-dropdown",
    terminal: "--z-terminal",
    overlay: "--z-overlay",
    modal: "--z-modal",
    toast: "--z-toast",
    skipLink: "--z-skip-link",
  },
  size: {
    headerHeight: "--size-header-height",
    statusBarHeight: "--size-status-bar-height",
    sidebarWidth: "--size-sidebar-width",
    sidebarCollapsed: "--size-sidebar-collapsed",
    terminalDefault: "--size-terminal-default",
    terminalExpanded: "--size-terminal-expanded",
    tapTarget: "--size-tap-target",
    iconSm: "--icon-size-sm",
    iconMd: "--icon-size-md",
    iconLg: "--icon-size-lg",
    iconXl: "--icon-size-xl",
  },
  container: {
    shell: "--container-shell",
    content: "--container-content",
    prose: "--container-prose",
    narrow: "--container-narrow",
    toc: "--container-toc",
  },
  layout: {
    proseWidth: "--prose-width",
    contentWidth: "--content-width",
    headingMaxWidth: "--heading-max-width",
    pagePaddingXMobile: "--page-padding-x-mobile",
    pagePaddingXTablet: "--page-padding-x-tablet",
    pagePaddingXDesktop: "--page-padding-x-desktop",
    cardMinHeight: "--card-min-height",
    gridGutter: "--grid-gutter",
    gridMargin: "--grid-margin",
  },
  breakpoint: {
    sm: "--breakpoint-sm",
    md: "--breakpoint-md",
    lg: "--breakpoint-lg",
    xl: "--breakpoint-xl",
    "2xl": "--breakpoint-2xl",
  },
  focus: {
    ringWidth: "--focus-ring-width",
    ringColor: "--focus-ring-color",
    ringOffset: "--focus-ring-offset",
    ringStyle: "--focus-ring-style",
  },
  a11y: {
    minContrastBody: "--a11y-min-contrast-body",
    minContrastLarge: "--a11y-min-contrast-large",
    skipLinkHeight: "--a11y-skip-link-height",
    minTapTarget: "--a11y-min-tap-target",
  },
} as const;

/** Resolve a token name to a CSS var() reference for inline styles or CSS-in-JS. */
export function cssVar(token: string): string {
  return `var(${token})`;
}

/** Tailwind utility class prefixes mapped to theme namespaces (theme.css). */
export const TAILWIND = {
  color: {
    base: "bg-base text-base border-base",
    surface: "bg-surface",
    elevated: "bg-elevated",
    accent: "bg-accent text-accent",
    primary: "text-primary",
    secondary: "text-secondary",
    operational: "text-operational",
  },
  spacing: {
    pageXMobile: "px-page-x-mobile",
    pageXTablet: "px-page-x-tablet",
    pageXDesktop: "px-page-x-desktop",
    header: "h-header",
    sidebar: "w-sidebar",
  },
  radius: {
    card: "rounded-lg",
    button: "rounded-md",
    modal: "rounded-xl",
  },
  duration: {
    fast: "duration-fast",
    base: "duration-base",
    slow: "duration-slow",
  },
  z: {
    header: "z-header",
    modal: "z-modal",
    toast: "z-toast",
  },
} as const;

export type TokenCategory = keyof typeof TOKEN;
