import type { Locale } from "./catalog";

const ru = {
  title: "Соберите свой проект",
  lead: "Выберите задачу и состав. Пришлём предложение по вашему расчёту.",
  kinds: {
    website: "Сайт",
    crm: "CRM на заказ",
    ai: "AI-интеграция",
    bot: "Telegram-бот",
    support: "Поддержка",
    audit: "Аудит проекта",
  },
  website: "Структура сайта",
  pages: "Количество страниц",
  pagesNote:
    "1 страница - лендинг. От 2 до 5 страниц входят в сайт компании. Далее +400 000 сум за страницу.",
  languages: "Языки",
  languagesNote:
    "Первый язык включён. Тексты и переводы предоставляет заказчик.",
  languageNames: { ru: "Русский", uz: "Узбекский", en: "Английский" },
  contentCms: "Редактирование текстов и картинок",
  contentCmsNote: "Админ-панель: меняйте содержимое страниц самостоятельно.",
  catalog: "Каталог товаров или услуг",
  catalogNote: "Категории, карточки, поиск и фильтры.",
  products: "Позиций в каталоге",
  productsNote:
    "Импорт из подготовленной таблицы. Написание описаний и обработка фотографий отдельно.",
  catalogCms: "Управление каталогом",
  catalogCmsNote:
    "Добавление позиций, цен, фотографий и категорий в админ-панели.",
  cart: "Корзина и оформление заказа",
  cartNote: "Заказ с контактами покупателя и уведомлением менеджера.",
  payment: "Онлайн-оплата",
  paymentNote:
    "Один платёжный сервис по готовому API. Договор с сервисом и комиссии отдельно.",
  booking: "Запись на услугу",
  bookingNote: "Выбор даты и времени, подтверждение заявки.",
  account: "Личный кабинет",
  accountNote: "Вход по email и история заказов. Другие роли оценим отдельно.",
  analytics: "Аналитика обращений",
  analyticsNote: "GA4: отправки форм и клики по контактам.",
  seo: "Расширенная SEO-настройка",
  seoNote:
    "Структура разделов, шаблоны метаданных и перенаправления. Без обещаний позиций.",
  migration: "Перенос со старого сайта",
  migrationNote:
    "До 50 страниц из готового экспорта. Медиа и сложные данные после проверки.",
  functionality: "Возможности",
  more: "Дополнительные работы",
  yes: "Да",
  no: "Нет",
  included: "Включено",
  base: "Базовая разработка",
  extraPages: "Дополнительные страницы",
  extraLanguages: "Дополнительные языки",
  catalogVolume: "Объём каталога",
  activity: "Чем занимается компания?",
  activityPlaceholder: "Например, турагентство: заявки, туристы и оплаты",
  size: "Сколько сотрудников?",
  sizes: {
    "10": "До 10",
    "50": "До 50",
    "100": "До 100",
    "100+": "Больше 100",
  },
  crmNote:
    "CRM рассчитываем после разговора о процессах. Опишите деятельность и выберите размер команды.",
  scenario: "Что должен делать AI?",
  scenarios: {
    support: "Отвечать клиентам",
    sales: "Помогать с заявками",
    knowledge: "Искать по документам компании",
    custom: "Другой сценарий",
  },
  channel: "Где будет работать?",
  channels: { web: "На сайте", telegram: "В Telegram", crm: "В вашей CRM" },
  sources: "Источников знаний",
  sourcesNote:
    "Один источник: сайт до 50 страниц или до 100 подготовленных документов, суммарно до 20 МБ. Другой объём оценим после просмотра.",
  requests: "Обращений в месяц",
  volumes: {
    "1000": "До 1 000",
    "5000": "До 5 000",
    "20000": "До 20 000",
    custom: "Больше 20 000 / пока не знаю",
  },
  integrations: "Внешних интеграций",
  integrationsNote:
    "Один сервис с документированным API. Например, создание заявки в CRM.",
  handoff: "Передача разговора сотруднику",
  handoffNote: "Если AI не может ответить, подключается человек.",
  updates: "Обновление базы знаний",
  updatesNote: "Повторная загрузка документов через панель.",
  preparation: "Подготовка документов",
  preparationNote:
    "Очистка и структурирование до 100 текстовых файлов. Сканирование и OCR отдельно.",
  aiNote:
    "Оценка за один AI-сценарий. Модель, хостинг и сообщения оплачиваются отдельно по использованию. Результат проверяем на согласованных примерах.",
  details: "Коротко о задаче",
  detailsPlaceholder: "Что сейчас занимает время и какой результат нужен?",
  botNote:
    "Оставьте имя и телефон. Менеджер уточнит, что должен делать бот, и подготовит стоимость.",
  supportPlan: "Объём поддержки",
  supportPlans: { basic: "До 3 часов в месяц", extended: "До 8 часов в месяц" },
  auditNote:
    "Разберём один процесс или существующий сайт. Подготовим рекомендации, этапы и оценку работ.",
  estimate: "Предварительная стоимость",
  manual: "Индивидуальная оценка",
  manualNote: "Сначала уточним задачу, затем зафиксируем состав и цену.",
  discount: "Скидка на базовый пакет",
  totalNote:
    "Стоимость за выбранный состав. Точную смету согласуем до начала работ. Домен, хостинг, лицензии и сторонние сервисы отдельно.",
  sendTitle: "Получить предложение",
  sendNote: "Расчёт придёт менеджеру вместе с вашими контактами.",
  submit: "Отправить заявку",
  success: "Заявка отправлена",
  successNote: "Менеджер скоро свяжется с вами и уточнит детали проекта.",
  monthly: "в месяц",
  once: "разово",
  selected: "Выбранный состав",
  required: "Заполните обязательные поля.",
};
type ConfiguratorCopy = typeof ru;
const en: ConfiguratorCopy = {
  title: "Configure your project",
  lead: "Choose what you need. We will prepare a proposal based on your selection.",
  kinds: {
    website: "Website",
    crm: "Custom CRM",
    ai: "AI integration",
    bot: "Telegram bot",
    support: "Support",
    audit: "Project audit",
  },
  website: "Website structure",
  pages: "Number of pages",
  pagesNote:
    "1 page: landing page. A company website includes 2 to 5 pages. Each further page costs 400 000 UZS.",
  languages: "Languages",
  languagesNote:
    "The first language is included. You provide the copy and translations.",
  languageNames: { ru: "Russian", uz: "Uzbek", en: "English" },
  contentCms: "Edit text and images",
  contentCmsNote: "An admin panel to update page content yourself.",
  catalog: "Product or service catalogue",
  catalogNote: "Categories, detail pages, search and filters.",
  products: "Catalogue items",
  productsNote:
    "Import from a prepared spreadsheet. Copywriting and photo editing are separate.",
  catalogCms: "Catalogue management",
  catalogCmsNote: "Add items, prices, photos and categories in an admin panel.",
  cart: "Shopping cart and checkout",
  cartNote: "Collect customer details and notify a manager.",
  payment: "Online payments",
  paymentNote:
    "One provider with a documented API. Provider agreement and fees are separate.",
  booking: "Service booking",
  bookingNote: "Date and time selection with a booking request.",
  account: "Customer account",
  accountNote:
    "Email sign-in and order history. Additional roles quoted separately.",
  analytics: "Enquiry analytics",
  analyticsNote: "GA4 events for forms and contact clicks.",
  seo: "Extended SEO setup",
  seoNote:
    "Section structure, metadata templates and redirects. No ranking promises.",
  migration: "Existing website migration",
  migrationNote:
    "Up to 50 pages from a prepared export. Media and complex data need review.",
  functionality: "Features",
  more: "Additional work",
  yes: "Yes",
  no: "No",
  included: "Included",
  base: "Base development",
  extraPages: "Additional pages",
  extraLanguages: "Additional languages",
  catalogVolume: "Catalogue volume",
  activity: "What does your company do?",
  activityPlaceholder:
    "For example, a travel agency: enquiries, travellers and payments",
  size: "Number of employees",
  sizes: {
    "10": "Up to 10",
    "50": "Up to 50",
    "100": "Up to 100",
    "100+": "More than 100",
  },
  crmNote:
    "A custom CRM needs a process review before pricing. Describe your business and select your team size.",
  scenario: "What should the AI do?",
  scenarios: {
    support: "Answer customers",
    sales: "Help with enquiries",
    knowledge: "Search company documents",
    custom: "Another scenario",
  },
  channel: "Where will it work?",
  channels: { web: "Website", telegram: "Telegram", crm: "Your CRM" },
  sources: "Knowledge sources",
  sourcesNote:
    "One source: a website of up to 50 pages or up to 100 prepared documents, 20 MB total. Larger volumes need review.",
  requests: "Monthly conversations",
  volumes: {
    "1000": "Up to 1 000",
    "5000": "Up to 5 000",
    "20000": "Up to 20 000",
    custom: "Over 20 000 / not sure",
  },
  integrations: "External integrations",
  integrationsNote:
    "One service with a documented API, such as creating a CRM enquiry.",
  handoff: "Human handover",
  handoffNote: "Pass a conversation to a person when the AI cannot help.",
  updates: "Knowledge base updates",
  updatesNote: "Upload updated documents through a panel.",
  preparation: "Document preparation",
  preparationNote:
    "Clean and structure up to 100 text files. Scanning and OCR are separate.",
  aiNote:
    "One AI scenario. Model, hosting and messaging costs are billed separately by usage. We test against agreed examples.",
  details: "Tell us about the task",
  detailsPlaceholder: "What takes time today and what should improve?",
  botNote:
    "Leave your name and phone number. A manager will discuss the bot's purpose and prepare a quote.",
  supportPlan: "Support scope",
  supportPlans: {
    basic: "Up to 3 hours a month",
    extended: "Up to 8 hours a month",
  },
  auditNote:
    "A review of one process or website, with recommendations, stages and a cost estimate.",
  estimate: "Estimated cost",
  manual: "Custom quote",
  manualNote: "We will clarify the task first, then agree the scope and price.",
  discount: "Base package discount",
  totalNote:
    "For the selected scope. We agree the final quote before work begins. Domain, hosting, licences and external services are separate.",
  sendTitle: "Request a proposal",
  sendNote: "Your selection and contact details go to the manager.",
  submit: "Send enquiry",
  success: "Enquiry sent",
  successNote: "A manager will contact you soon to discuss the project.",
  monthly: "per month",
  once: "one-off",
  selected: "Your selection",
  required: "Complete the required fields.",
};
const uz: ConfiguratorCopy = {
  title: "Loyihangizni hisoblang",
  lead: "Vazifa va kerakli imkoniyatlarni tanlang. Hisob asosida taklif tayyorlaymiz.",
  kinds: {
    website: "Sayt",
    crm: "Maxsus CRM",
    ai: "AI integratsiyasi",
    bot: "Telegram bot",
    support: "Qo‘llab-quvvatlash",
    audit: "Loyiha auditi",
  },
  website: "Sayt tuzilishi",
  pages: "Sahifalar soni",
  pagesNote:
    "1 sahifa - lending. Kompaniya saytiga 2 dan 5 tagacha sahifa kiradi. Keyingi har bir sahifa +400 000 so‘m.",
  languages: "Tillar",
  languagesNote:
    "Birinchi til narxga kiradi. Matnlar va tarjimalarni mijoz taqdim etadi.",
  languageNames: { ru: "Ruscha", uz: "O‘zbekcha", en: "Inglizcha" },
  contentCms: "Matn va rasmlarni tahrirlash",
  contentCmsNote: "Sahifalarni mustaqil yangilash uchun boshqaruv paneli.",
  catalog: "Mahsulot yoki xizmatlar katalogi",
  catalogNote: "Toifalar, kartochkalar, qidiruv va filtrlar.",
  products: "Katalogdagi pozitsiyalar",
  productsNote:
    "Tayyor jadvaldan import. Tavsif yozish va rasmlarni tahrirlash alohida.",
  catalogCms: "Katalogni boshqarish",
  catalogCmsNote: "Panel orqali mahsulot, narx, rasm va toifalarni qo‘shish.",
  cart: "Savat va buyurtma",
  cartNote: "Mijoz kontaktlari bilan buyurtma va menejerga bildirishnoma.",
  payment: "Onlayn to‘lov",
  paymentNote:
    "Tayyor API orqali bitta to‘lov xizmati. Shartnoma va komissiyalar alohida.",
  booking: "Xizmatga yozilish",
  bookingNote: "Sana va vaqtni tanlash, arizani tasdiqlash.",
  account: "Shaxsiy kabinet",
  accountNote:
    "Email orqali kirish va buyurtmalar tarixi. Boshqa rollar alohida baholanadi.",
  analytics: "Murojaatlar tahlili",
  analyticsNote: "GA4: shakl yuborish va kontakt bosish hodisalari.",
  seo: "Kengaytirilgan SEO sozlash",
  seoNote:
    "Bo‘limlar tuzilishi, metama’lumot shablonlari va yo‘naltirishlar. Reyting kafolatisiz.",
  migration: "Eski saytdan ko‘chirish",
  migrationNote:
    "Tayyor eksportdan 50 tagacha sahifa. Media va murakkab ma’lumotlar tekshiruvdan so‘ng.",
  functionality: "Imkoniyatlar",
  more: "Qo‘shimcha ishlar",
  yes: "Ha",
  no: "Yo‘q",
  included: "Narxga kiradi",
  base: "Asosiy ishlab chiqish",
  extraPages: "Qo‘shimcha sahifalar",
  extraLanguages: "Qo‘shimcha tillar",
  catalogVolume: "Katalog hajmi",
  activity: "Kompaniya nima bilan shug‘ullanadi?",
  activityPlaceholder:
    "Masalan, sayyohlik agentligi: arizalar, sayyohlar va to‘lovlar",
  size: "Xodimlar soni",
  sizes: {
    "10": "10 tagacha",
    "50": "50 tagacha",
    "100": "100 tagacha",
    "100+": "100 dan ortiq",
  },
  crmNote:
    "CRM narxini jarayonlarni muhokama qilgandan keyin hisoblaymiz. Faoliyatingizni yozing va jamoa hajmini tanlang.",
  scenario: "AI nima qilishi kerak?",
  scenarios: {
    support: "Mijozlarga javob berish",
    sales: "Arizalar bilan yordam berish",
    knowledge: "Kompaniya hujjatlaridan izlash",
    custom: "Boshqa vazifa",
  },
  channel: "Qayerda ishlaydi?",
  channels: { web: "Saytda", telegram: "Telegramda", crm: "CRM tizimingizda" },
  sources: "Bilim manbalari",
  sourcesNote:
    "Bitta manba: 50 sahifagacha sayt yoki 100 tagacha tayyor hujjat, jami 20 MB. Kattaroq hajmni ko‘rib baholaymiz.",
  requests: "Oylik murojaatlar",
  volumes: {
    "1000": "1 000 tagacha",
    "5000": "5 000 tagacha",
    "20000": "20 000 tagacha",
    custom: "20 000 dan ortiq / noma’lum",
  },
  integrations: "Tashqi integratsiyalar",
  integrationsNote:
    "Hujjatlangan API bilan bitta xizmat. Masalan, CRMda ariza yaratish.",
  handoff: "Suhbatni xodimga topshirish",
  handoffNote: "AI javob bera olmasa, xodim suhbatga qo‘shiladi.",
  updates: "Bilim bazasini yangilash",
  updatesNote: "Panel orqali hujjatlarni qayta yuklash.",
  preparation: "Hujjatlarni tayyorlash",
  preparationNote:
    "100 tagacha matnli faylni tozalash va tuzish. Skanerlash va OCR alohida.",
  aiNote:
    "Bitta AI ssenariysi uchun baho. Model, hosting va xabarlar foydalanishga qarab alohida to‘lanadi. Kelishilgan misollarda tekshiramiz.",
  details: "Vazifa haqida qisqacha",
  detailsPlaceholder: "Hozir nima vaqt oladi va qanday natija kerak?",
  botNote:
    "Ism va telefoningizni qoldiring. Menejer bot vazifasini aniqlashtirib, narxni tayyorlaydi.",
  supportPlan: "Yordam hajmi",
  supportPlans: { basic: "Oyiga 3 soatgacha", extended: "Oyiga 8 soatgacha" },
  auditNote:
    "Bitta jarayon yoki saytni ko‘rib chiqamiz. Tavsiyalar, bosqichlar va xarajat bahosini tayyorlaymiz.",
  estimate: "Dastlabki narx",
  manual: "Individual baholash",
  manualNote:
    "Avval vazifani aniqlashtiramiz, so‘ng hajm va narxni kelishamiz.",
  discount: "Asosiy paketga chegirma",
  totalNote:
    "Tanlangan hajm uchun narx. Ish boshlanishidan oldin aniq smetani kelishamiz. Domen, hosting, litsenziya va tashqi xizmatlar alohida.",
  sendTitle: "Taklif olish",
  sendNote: "Hisob va kontaktlaringiz menejerga yuboriladi.",
  submit: "Ariza yuborish",
  success: "Ariza yuborildi",
  successNote:
    "Menejer tez orada bog‘lanib, loyiha tafsilotlarini aniqlashtiradi.",
  monthly: "oyiga",
  once: "bir martalik",
  selected: "Tanlangan tarkib",
  required: "Majburiy maydonlarni to‘ldiring.",
};
export const CONFIGURATOR_COPY: Record<Locale, ConfiguratorCopy> = {
  ru,
  en,
  uz,
};
